/** CREATE TABLE WITH CLUSTERING **/

CREATE TABLE EMPLOYEE (TYPE,NAME,COUNTRY,DATE) CLUSTER BY (DATE);

/** IF YOU HAVE ALREADY LOADED DATA **/

ALTER  TABLE EMPLOYEE CLUSTER BY (DATE);

ALTER  TABLE TEST RECLUSTER;

SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER LIMIT 100

/**** CREATE TABLE WITHOUT CLUSTER ***/

DESC TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER

CREATE OR REPLACE TRANSIENT TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER;

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT)');

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT,C_CUSTKEY)');

/**** CREATE TABLE WITH CLUSTER ***/

select get_ddl('TABLE','SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER')

drop table CUSTOMER_CLUSTERED

create or replace transient TABLE CUSTOMER_CLUSTERED (
	C_CUSTKEY NUMBER(38,0) NOT NULL,
	C_NAME VARCHAR(25) NOT NULL,
	C_ADDRESS VARCHAR(40) NOT NULL,
	C_NATIONKEY NUMBER(38,0) NOT NULL,
	C_PHONE VARCHAR(15) NOT NULL,
	C_ACCTBAL NUMBER(12,2) NOT NULL,
	C_MKTSEGMENT VARCHAR(10),
	C_COMMENT VARCHAR(117)
) CLUSTER BY (C_MKTSEGMENT)

INSERT INTO  SAMPLE_DATABASE.PUBLIC.CUSTOMER_CLUSTERED
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER
-- ORDER BY C_MKTSEGMENT

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_CLUSTERED','(C_MKTSEGMENT)');

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_CLUSTERED');

/** RECLUSTER THE NON CLUSTERED TABLE **/

CREATE OR REPLACE TRANSIENT TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_ORDERED
AS
SELECT * FROM SNOWFLAKE_SAMPLE_DATA.TPCH_SF10000.CUSTOMER ORDER BY C_MKTSEGMENT

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_ORDERED','(C_MKTSEGMENT)');


/** RECLUSTER TABLE AFTER LOADING DATA **/

SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER

ALTER  TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER BY (C_MKTSEGMENT);

ALTER  TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER RECLUSTER;

SELECT SYSTEM$CLUSTERING_INFORMATION('CUSTOMER_NOCLUSTER','(C_MKTSEGMENT)');

/****** Cardinality of columns **********/

DESC TABLE SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER

SELECT C_MKTSEGMENT,COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER
GROUP BY C_MKTSEGMENT

SELECT C_MKTSEGMENT,C_ADDRESS,COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER
GROUP BY C_MKTSEGMENT,C_ADDRESS

SELECT COUNT(*) FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER

SELECT DISTINCT C_ADDRESS FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER 

SELECT 238609294/1500000000

SELECT DISTINCT C_MKTSEGMENT FROM SAMPLE_DATABASE.PUBLIC.CUSTOMER_NOCLUSTER CLUSTER

SELECT 5/1500000000