CREATE DATABASE DEMO_DB;

CREATE TABLE DEMO_DB.PUBLIC.LINEITEM_SOS
AS
SELECT * FROM
SNOWFLAKE_SAMPLE_DATA.TPCH_SF1000.LINEITEM;

CREATE TABLE DEMO_DB.PUBLIC.LINEITEM_NO_SOS CLONE DEMO_DB.PUBLIC.LINEITEM_SOS;

UPDATE DEMO_DB.PUBLIC.LINEITEM_SOS 
SET L_COMMENT='GOOD PRODUCTS'
WHERE l_orderkey = '4509487233';

UPDATE DEMO_DB.PUBLIC.LINEITEM_NO_SOS 
SET L_COMMENT='GOOD PRODUCTS'
WHERE l_orderkey = '4509487233';

ALTER TABLE DEMO_DB.PUBLIC.LINEITEM_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(L_COMMENT);

ALTER TABLE DEMO_DB.PUBLIC.LINEITEM_SOS ADD SEARCH OPTIMIZATION ON EQUALITY(l_orderkey);

show tables;

select * from DEMO_DB.PUBLIC.lINEITEM_SOS where L_orderkey = '4509487233' 

select * from DEMO_DB.PUBLIC.lINEITEM_SOS where l_COMMENT = 'GOOD PRODUCTS' 


select * from DEMO_DB.PUBLIC.lINEITEM_NO_SOS where L_orderkey = '4509487233'

select * from DEMO_DB.PUBLIC.lINEITEM_NO_SOS where L_COMMENT = 'GOOD PRODUCTS'